const ADD_PONEY = "ADD_PONEY";
const DELETE_PONEY = "DELETE_PONEY";

const LOADING = "LOADING";
const SET_ERROR = "SET_ERROR";
const LOAD_PONEYS = "LOAD_PONEYS";

const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";

export {
  ADD_PONEY,
  DELETE_PONEY,
  LOADING,
  SET_ERROR,
  LOAD_PONEYS,
  LOGIN,
  LOGOUT
};
