const ADD_PONEY = "ADD_PONEY";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOAD_PONEYS = "LOAD_PONEYS";
const TOGGLE_VIEW_DELETED_PONEYS = "TOGGLE_VIEW_DELETED_PONEYS";

export { ADD_PONEY, LOGIN, LOGOUT, LOAD_PONEYS, TOGGLE_VIEW_DELETED_PONEYS };
